version: 1.3.3.0304_base
profile: local
server:
  static_folder: templates
  context_path: /api/v1.3.3
  cors:
    allow: true
    origins: '*'
    path: /api/*

sqlalchemy:
  SQLALCHEMY_DATABASE_URI: mysql://dev:dev@119.29.94.246:3306/test_db?charset=utf8
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SQLALCHEMY_ECHO: true
#  SQLALCHEMY_POOL_SIZE: 50
#  SQLALCHEMY_POOL_TIMEOUT: 20
#  SQLALCHEMY_RECORD_QUERIES:
#  SQLALCHEMY_NATIVE_UNICODE:
#  SQLALCHEMY_POOL_RECYCLE:
#  SQLALCHEMY_MAX_OVERFLOW:
jwt:
  secret_key: ft@4&iP!_  # Token密钥
  ttl: 86400  # Token有效期(单位: 秒)
  algorithm: HS256  # Token加密算法
  token_prefix: Bearer  # Token前缀