version: 1.2.0.0301_base

profile: dev

server:
  static_folder: /templates
  context-path: /api/${version}
  port: 5000
  cors:
    allow: true
    origins: *
    path: /api/*

sqlalchemy:
  SQLALCHEMY_DATABASE_URI: mysql://dev:dev@119.29.94.246:3306/test_db?charset=utf8
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SQLALCHEMY_ECHO: True
  SQLALCHEMY_POOL_SIZE: 50,
  SQLALCHEMY_POOL_TIMEOUT: 20
  SQLALCHEMY_RECORD_QUERIES: ''
  SQLALCHEMY_NATIVE_UNICODE: ''
  SQLALCHEMY_POOL_RECYCLE: ''
  SQLALCHEMY_MAX_OVERFLOW: ''
