USERNAME = 'dev'
PASSWORD = 'dev'
HOST = '119.29.94.246'
PORT = '3306'
DATABASE = 'test_db'

DB_URI = 'mysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOST, PORT, DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
